rm(list = ls())
set.seed(1024)


### ARIMA SIM (MA(1))
X <- arima.sim(n=128, model=list(ma=c(0.62)))
h<-acf(X)
plot(h, col=4, type="h", lwd=2, main="ACF-MA(1)")
g<-pacf(X)
plot(g, col=4, type="h", lwd=2, main="PACF-MA(1)")
print(h)
print(g)

### ARIMA SIM (AR)
X <- arima.sim(n=128, model=list(ar=c(0.71)))
h<-acf(X)
plot(h, col=4, type="h", lwd=2, main="ACF-AR(1)")
g<-pacf(X)
plot(g, col=2, type="h", lwd=2, main="PACF-AR(1)")

### ARMA(1,1)
X <- arima.sim(n=1024, model=list(ar=c(0.71), ma=c(-0.87)))
h<-acf(X)
plot(h, col=4, type="h", lwd=2, main="ACF-ARMA(1,1)")
g<-pacf(X)
plot(g, col=2, type="h", lwd=2, main="PACF-ARMA(1,1)")

### AR(2)
X <- arima.sim(n=128, model=list(ar=c(0.89, -0.64)))
h<-acf(X)
plot(h, col=4, type="h", lwd=2, main="ACF-AR(2)")
g<-pacf(X)
plot(g, col=2, type="h", lwd=2, main="PACF-AR(2)")

### MA(2)
X <- arima.sim(n=128, model=list(ma=c(0.62, 2.2)))
h<-acf(X)
plot(h, col=4, type="h", lwd=2, main="ACF-MA(2)")
g<-pacf(X)
plot(g, col=4, type="h", lwd=2, main="PACF-MA(2)")